title: "Swati Ghosh, PhD"
description: "Translational liver disease scientist"

url: "https://piousbala.github.io"
baseurl: "/Swati-Website"

markdown: kramdown
kramdown:
  input: GFM
plugins: []
exclude:
  - README.md
